const dados = [
    {
      id: 1,
      imgSrc: "jaqueta.png",
      filtro: "Jaquetas",
      nome: "Lightweight Jacket",
      descricao: "Adicione um pouco de energia ao seu guarda-roupa de inverno com esta jaqueta vibrante...",
      preco: 250.00,
      botão:"Adicionar ao carrinho",
    },
    {
      id: 2,
      imgSrc: "touca.png",
      filtro: "Acessórios",
      nome: "Black Hat",
      descricao: "O gorro Next.js chegou! Esta beldade bordada tem um ajuste confortável que garante que...",
      preco: 40.00,
      botão:"Adicionar ao carrinho",
    },
    {
      id: 3,
      imgSrc: "mascara.png",
      filtro: "Acessórios",
      nome: "Mask",
      descricao: "Esta máscara facial durável é feita de duas camadas de tecido tratado e possui presilhas...",
      preco: 20.00,
      botão:"Adicionar ao carrinho",
    },
    {
      id: 4,
      imgSrc: "camisa preta.png",
      filtro: "Camisetas",
      nome: "T-Shirt",
      descricao: "Esta t-shirt é imprescindível no seu guarda-roupa, combinando o caimento intemporal de...",
      preco: 50.00,
      botão:"Adicionar ao carrinho",
    },
    {
      id: 5,
      imgSrc: "camisa branca.png",
      filtro: "Camisetas",
      nome: "Short-Sleeve T-Shirt",
      descricao: "Agora você encontrou a camiseta básica do seu guarda-roupa. É feito de um mais grosso...",
      preco: 50.00,
      botão:"Adicionar ao carrinho",
    },
    {
      id:6 ,
      imgSrc: "jaqueta preta champion.png",
      filtro: "Jaquetas",
      nome: "Champion Packable Jacket",
      descricao: "Proteja-se dos elementos com esta jaqueta embalável Champion. Esta jaqueta de poliést...",
      preco: 300.00,
      botão:"Adicionar ao carrinho",
    },
    
  ];